---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data
  labels:
    app: prometheus
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /pv1
  storageClassName: local  

